version: 3

env:
  PRODUCTION: false

vars:
  APP_PORT: 8080
  APP_CMD: go run .
  APP_HOST: localhost
  PROXY_PORT: 8081
  TEMPL_DIR: ./templ
  TEMPL_OPEN_BROWSER: false
  DIST_DIR: ./dist
  STATIC_DIR: ./static
  ASSETS_DIR: ./assets

tasks:
  default:
    cmds:
      - live

  live:templ:
    desc: Live reload the templates
    cmds:
      - go tool templ generate --watch --proxy="http://{{.APP_HOST}}:{{.APP_PORT}}" --cmd="{{.APP_CMD}}" --proxybind="{{.APP_HOST}}" --proxyport="{{.PROXY_PORT}}" --open-browser="{{.TEMPL_OPEN_BROWSER}}"

  live:esbuild:
    desc: Bundle and watch JS/TS files
    env:
      APP_HOST: '{{.APP_HOST}}'
      PROXY_PORT: '{{.PROXY_PORT}}'
    cmds:
      - node build.js dev

  build:esbuild:
    desc: Build JS/TS files for production
    env:
      DEV: "false"
      PRODUCTION: true
    cmds:
      - node build.js build

  build:templ:
    desc: Build the templates
    env:
      PRODUCTION: true
    cmds:
      - go tool templ generate --cmd="{{.APP_CMD}}"

  live:
    desc: Live reload the go code, templates, and assets
    deps:
      - live:templ
      - live:esbuild

  live:
    desc: Live reload the go code, templates, and assets
    deps:
      - live:templ
      - live:esbuild

  build:
    desc: Build the go code, templates, and assets
    deps:
      - build:esbuild
      - build:templ

  format:templ:
    desc: Format all templ files
    cmds:
      - templ fmt {{.TEMPL_DIR}}
